### PR TITLE
In /wp-admin/admin.php?page=crellyslider&view=edit&id=1

### PR DESCRIPTION
**Pull request by eduardoarandah**
table "slide options" css was missing a clear:left

### CODE REVIEW

**Comment by eduardoarandah** [comment]
Amazing work! 
before
after

**Comment by eduardoarandah** [comment]
Hi!
I created the language files 100% complete for spanish and fixed the loading of language files. 
it's ready to pull =)

**Comment by fabiorino** [comment]
Hi, thank you really much for what you are doing. 2 things (I'm relatively new to GitHub and I don't know if the discussion is the right section to ask):

1)I'd like to keep the language folder into the wordpress folder. In this way, the JS plugin and the backend interface are as much as standalone as possible.

2) The load_language_files should() be called crellyslider_loadLanguageFiles(). Prefixes avoid conflicts.

I'd do these little things by myself but I'm not sure if I have to merge the pull request or I have to wait your modifications and then merge (again, sorry, but this is my first project on GitHub).

**Comment by eduardoarandah** [comment]
Yes, this is the perfect place for discussions.
Or "issues" you can make as many as you want.

I suggest you merge my changes, commit, make your changes, commit, then
push to github.

I will keep an eye on this project, I like it a lot!
It is fast, light and easy to use. Keep it simple!

I used it here: http://smilexalapa.com/


El jueves, 5 de marzo de 2015, fabiorino <notifications@github.com>
escribió:

> Hi, thank you really much for what you are doing. 2 things (I'm relatively
> new to GitHub and I don't know if the discussion is the right section to
> ask):
>
> 1)I'd like to keep the language folder into the wordpress folder. In this
> way, the JS plugin and the backend interface are as much as standalone as
> possible.
>
> 2) The load_language_files should() be called
> crellyslider_loadLanguageFiles(). Prefixes avoid conflicts.
>
> I'd do these little things by myself but I'm not sure if I have to merge
> the pull request or I have to wait your modifications and then merge
> (again, sorry, but this is my first project on GitHub).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fabiorino/crelly-slider/pull/5#issuecomment-77431070>.
>


-- 
Enviado desde mi móvil

**Pull request merged**
