### PR TITLE
Admin improvements and adding SK localization

### PR DESCRIPTION
**Pull request by webmandesign**
Hi,

As of https://wordpress.org/support/topic/admin-iterface?replies=4, I'm creating a pull request fixing these issues for you to consider to merge it up and include it in the next plugin update.

I've also created a Slovak plugin translation.

Thanks!

Oliver

### CODE REVIEW

**Comment by fabiorino** [comment]
Hi, thank you very much for all the work you are doing. I can't merge the max-width to avoid the scrollbar because the text and image elements in the preview area are not scaled so the proportions wouldn't be correct.

**Comment by webmandesign** [comment]
Hi,

OK, I understand. Then we need to come up with some different solution ;) as this way it is not very user friendly. I'll try to have a look at this too.

Regards,

Oliver

**Comment by fabiorino** [comment]
Hello, how is it going? I hope you'll read this message even if this is a very old thread (I didn't know another way to contact you).
I’d like to ask you if you are still interested in updating the translation of my plugin: this week I’m going to release an update that contains some new strings. Can you help me? You would do me a big favour!

Thank you really much,
Fabio.

my e-mail address is: fabiorino@outlook.com

**Comment by webmandesign** [comment]
Sure, Fabio! I've replied to your email.

**Pull request closed without merging**
